### ISSUE TITLE
Versa 2 Support

### ISSUE THREAD

**Issue by Roang-zero1** [urbandroid-team/SleepAsFitbit#15]
The currently available app is not compatible for the new Versa 2 devices.
Is there a plan for implementing this?

I am available for testing, but would need support with getting the dev environment up and running.

**Comment by DempseyWilliams** [comment]
I'm interested in versa 2 support as well.

**Comment by Roang-zero1** [comment]
Thanks for the feedback, looking forward to it.

**Comment by Roang-zero1** [comment]
I don't know if this helps for this situation, but the new SDK is available from the fitbit-sdk repository at: https://github.com/Fitbit/fitbit-sdk-toolchain/releases

**Comment by Artaud** [comment]
Hi, sorry for sluggishness. I've released an updated version of the watch app with the new SDK and Versa 2 support.

**Comment by Roang-zero1** [comment]
Thanks will try it out!
